add 3 buttons for main menu
uptechteam/QuizApp pull request #1
Opened 2021-11-24 08:11 UTC by PanVova

2021-11-25 16:02 UTC, NickHuk requested changes

2021-11-25 16:02 UTC, NickHuk commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
square-android codestyle

2021-11-25 16:02 UTC, NickHuk commented on app/src/main/java/com/panhuk/quizapp/MainActivity.kt
> +    }
Composable functions NameFormats match google best practices! Well done 😍

2021-11-26 08:58 UTC, PanVova commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
What does it mean square-android ?

2021-11-29 08:52 UTC, merged