features: divide api -> api, apiDI modules
uptechteam/QuizApp pull request #12
Opened 2021-12-07 10:47 UTC by PanVova

2021-12-09 09:35 UTC, NickHuk requested changes

2021-12-09 09:35 UTC, NickHuk commented on apiDI/src/main/java/com/example/apidi/base/BaseApiModule.kt
> +package com.example.apidi.base
`com.example` WTF? Please name package `com.panhuk...`

2021-12-09 09:35 UTC, NickHuk commented on repositoryDI/build.gradle
> -  implementation project(':api')
removed `:api` dependencies - well done !

2021-12-09 10:54 UTC, PanVova commented on apiDI/src/main/java/com/example/apidi/base/BaseApiModule.kt
> +package com.example.apidi.base
renamed

2021-12-10 09:16 UTC, NickHuk approved these changes
GJ!

2021-12-10 09:52 UTC, merged